In [3]:
import numpy as np

In [68]:
class Model():
    def __init__(self):
        self.reward_map = -np.ones((4,4))
        #self.reward_map[((0,3),(0,3))] = 0
        self.V = np.zeros(self.reward_map.shape)
        self.gamma = 1
        self.epsilon = .001
        #print(self.reward_map)
        
    def train(self):
        
        while True:
            V_update = np.zeros(self.reward_map.shape)

            actions = np.array([[-1,0],[+1,0],[0,1],[0,-1]])
            p = [.25,.25,.25,.25]

            for i in range(self.reward_map.shape[0]):
                for j in range(self.reward_map.shape[1]):

                    state = [i,j]

                    #print(state)

                    if state != [0,0] and state != [3,3]:    
                        # V update
                        for a,action_prob in zip(actions,p):
                            next_state = [state[0]+a[0],state[1]+a[1]]

                            next_state[0] = state[0] if next_state[0] == -1 else next_state[0]
                            next_state[1] = state[1] if next_state[1] == -1 else next_state[1]
                            next_state[0] = state[0] if next_state[0] == 4 else next_state[0]
                            next_state[1] = state[1] if next_state[1] == 4 else next_state[1]

                            #print(next_state)
                            #print(f"{action_prob}*({self.reward_map[tuple(next_state)]} + {self.gamma} * {self.V[next_state]})")
                            V_update[tuple(state)] += action_prob*(self.reward_map[tuple(next_state)] + self.gamma * self.V[tuple(next_state)])
            
            err = np.max(np.absolute(V_update-self.V))
            self.V = V_update

            if err < self.epsilon:
                print(V_update)
                break

In [69]:
model = Model()

In [70]:
model.train()

[[  0.         -13.98945772 -19.98437823 -21.98251832]
 [-13.98945772 -17.98623815 -19.98448273 -19.98437823]
 [-19.98437823 -19.98448273 -17.98623815 -13.98945772]
 [-21.98251832 -19.98437823 -13.98945772   0.        ]]
