### Markov Desicion Process

In [4]:
import numpy as np

In [5]:
reward_map = - .04 * np.ones((3,4))
reward_map[1,1]= -1
reward_map[0,3]= +1
reward_map[1,3]= -1
R = np.reshape(reward_map,(reward_map.shape[0]*reward_map.shape[1],1))

In [6]:
def transition_probabilities(action):
    P = np.zeros((reward_map.shape[0]*reward_map.shape[1],reward_map.shape[0]*reward_map.shape[1]))
    
    for i in range(reward_map.shape[0]):
        for j in range(reward_map.shape[1]):
            Ps = np.zeros((reward_map.shape[0]+2,reward_map.shape[1]+2))
            state = [i,j]
            if action == 0:
                Ps[state[0],state[1]+1] = .8
                Ps[state[0]+1,state[1]] = .1
                Ps[state[0]+1,state[1]+2] = .1
            elif action == 1:
                Ps[state[0]+2,state[1]+1] = .8
                Ps[state[0]+1,state[1]] = .1
                Ps[state[0]+1,state[1]+2] = .1
            elif action == 2:
                Ps[state[0]+1,state[1]+2] = .8
                Ps[state[0],state[1]+1] = .1
                Ps[state[0]+2,state[1]+1] = .1
            elif action == 3:
                Ps[state[0]+1,state[1]] = .8
                Ps[state[0],state[1]+1] = .1
                Ps[state[0]+2,state[1]+1] = .1

            Ps[state[0]+1,state[1]+1] = np.sum(Ps) - np.sum(Ps[1:-1,1:-1]) 

            #print(Ps[1:-1,1:-1])
            #print(Ps[1:-1,1:-1].flatten())
            P[reward_map.shape[1]*i+j,:] = Ps[1:-1,1:-1].flatten()
            #print("-"*10)
    #print(P)
    return(P)
transition_probabilities(0)

array([[0.9, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.1, 0.8, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.1, 0.8, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.1, 0.9, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.8, 0. , 0. , 0. , 0.1, 0.1, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.8, 0. , 0. , 0.1, 0. , 0.1, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.8, 0. , 0. , 0.1, 0. , 0.1, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.8, 0. , 0. , 0.1, 0.1, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.8, 0. , 0. , 0. , 0.1, 0.1, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.8, 0. , 0. , 0.1, 0. , 0.1, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.8, 0. , 0. , 0.1, 0. , 0.1],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.8, 0. , 0. , 0.1, 0.1]])

In [7]:
def training(V,iterations,gamma,action):
    Vs = np.zeros((reward_map.shape[0]*reward_map.shape[1],4,1))
    
    for i in range(iterations):
        V = R + gamma * np.matmul(transition_probabilities(action),V)
    return V

Vs = np.zeros((reward_map.shape[0]*reward_map.shape[1],4,1))
g = .4
Vs[:,0] = training(Vs[:,0],100,g,0)
Vs[:,1] = training(Vs[:,1],100,g,1)
Vs[:,2] = training(Vs[:,2],100,g,2)
Vs[:,3] = training(Vs[:,3],100,g,3)


In [8]:
np.matmul(transition_probabilities(0),Vs[:,0])

array([[-0.06577851],
       [-0.0524561 ],
       [ 0.17402473],
       [ 1.41087655],
       [-0.16645546],
       [-0.06870288],
       [-0.13146763],
       [ 1.18981436],
       [-0.13217769],
       [-0.84062082],
       [-0.13371981],
       [-0.45063354]])

In [9]:
np.matmul(transition_probabilities(1),Vs[:,1])

array([[-0.13246527],
       [-0.8418691 ],
       [-0.08579316],
       [-0.79519699],
       [-0.16716217],
       [-0.07855863],
       [-0.26347035],
       [-0.17486682],
       [-0.06666667],
       [-0.06666667],
       [-0.06666667],
       [-0.06666667]])

In [100]:
Vs = np.reshape(Vs,(reward_map.shape[0]*reward_map.shape[1],4))

In [101]:
Vs

array([[-0.0663114 , -0.09298611, -0.04105236, -0.06666667],
       [-0.06098244, -0.37674764,  0.05372396, -0.10680045],
       [ 0.02960989, -0.07431726,  0.43045181, -0.0929751 ],
       [ 1.56435062,  0.6819212 ,  1.47546296,  0.96539408],
       [-0.10658218, -0.10686487, -0.41504825, -0.06666667],
       [-1.02748115, -1.03142345, -1.15423955, -1.02987737],
       [-0.09258705, -0.14538814, -0.47286015, -0.37699877],
       [-0.52407425, -1.06994673, -1.39259259, -1.08674141],
       [-0.09287107, -0.06666667, -0.10123754, -0.06666667],
       [-0.37624833, -0.06666667, -0.1268316 , -0.10680045],
       [-0.09348793, -0.06666667, -0.11121485, -0.0929751 ],
       [-0.22025342, -0.06666667, -0.14953704, -0.11793926]])

In [102]:
Vs.argmax(axis=-1)

array([2, 2, 2, 0, 3, 0, 0, 0, 1, 1, 1, 1])

In [103]:
np.reshape(Vs.argmax(axis=-1),(reward_map.shape[0],reward_map.shape[1]))

array([[2, 2, 2, 0],
       [3, 0, 0, 0],
       [1, 1, 1, 1]])